import type { Plugin, ViteDevServer } from 'vite'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { glob } from 'glob'
import type { PluginOptions } from './types'

export type { PluginOptions, SvgProps, SvgColor, SvgBase64, NumberWithUnit, SvgGlobResult } from './types'

function generateSvgTypes(svgDir: string, outputPath: string, root: string) {
  const fullSvgDir = resolve(root, svgDir)
  const fullOutputPath = resolve(root, outputPath)
  
  const svgFiles = glob.sync(`${fullSvgDir}/**/*.svg`)
  const svgNames = svgFiles.map((file) => {
    const relativePath = file.replace(fullSvgDir, '')
    const lastSlashIndex = Math.max(relativePath.lastIndexOf('/'), relativePath.lastIndexOf('\\'))
    return relativePath.slice(lastSlashIndex + 1, -4)?.toLowerCase() ?? null
  }).filter(Boolean)

  const svgNameType = svgNames.length > 0
    ? svgNames.map(name => `'${name}'`).join(' | ')
    : 'string'

  // Calculate relative path from output to svg dir
  const outputDir = dirname(fullOutputPath)
  const relativeSvgDir = resolve(root, svgDir).replace(/\\/g, '/')
  const relativeOutputDir = outputDir.replace(/\\/g, '/')
  
  // Calculate relative import path
  let importPath = relativeSvgDir.replace(root.replace(/\\/g, '/'), '')
  if (!importPath.startsWith('/')) importPath = '/' + importPath
  
  // Generate single .ts file with types, init, and re-export
  const moduleContent = `// Auto-generated by vite-plugin-for-svelte-svg
// Do not edit manually

import { Svg as BaseSvg, initSvg } from 'vite-plugin-for-svelte-svg/runtime'
import type { HTMLAttributes } from 'svelte/elements'
import type { Component } from 'svelte'

// Initialize SVG registry
initSvg(import.meta.glob('${importPath}/**/*.svg'))

export type SvgName = ${svgNameType}

export interface SvgProps extends Omit<HTMLAttributes<HTMLElement>, 'color'> {
  name: SvgName
  size?: string | number
  color?: string | string[]
}

export const Svg = BaseSvg as Component<SvgProps>
`

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true })
  }

  // Use .ts extension instead of .d.ts
  const tsOutputPath = fullOutputPath.replace('.d.ts', '.ts')
  writeFileSync(tsOutputPath, moduleContent)
  console.log(`[vite-plugin-for-svelte-svg] Generated: ${outputPath.replace('.d.ts', '.ts')}`)
}

export default function svelteSvgPlugin(options: PluginOptions = {}): Plugin {
  const {
    dir = 'src/svg',
    typesOutput = 'src/types/svg.d.ts',
    generateTypes = true
  } = options

  let root = process.cwd()

  return {
    name: 'vite-plugin-for-svelte-svg',

    configResolved(config) {
      root = config.root
    },

    buildStart() {
      if (generateTypes) {
        generateSvgTypes(dir, typesOutput, root)
      }
    },

    configureServer(server: ViteDevServer) {
      if (!generateTypes) return

      const fullSvgDir = resolve(root, dir)
      
      server.watcher.add(fullSvgDir)
      
      const handleChange = () => {
        generateSvgTypes(dir, typesOutput, root)
        server.ws.send({ type: 'full-reload' })
      }

      server.watcher.on('add', (path) => {
        if (path.startsWith(fullSvgDir) && path.endsWith('.svg')) {
          handleChange()
        }
      })

      server.watcher.on('unlink', (path) => {
        if (path.startsWith(fullSvgDir) && path.endsWith('.svg')) {
          handleChange()
        }
      })
    }
  }
}
